name: Remove Needs Labels

jobs:
  remove_labels:
    runs-on: ubuntu-latest
    steps:
      - name: 'Remove needs labels on issue close' 
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: |
            needs PR
            needs spike