name: Remove Needs PR Label

on:
  issues:
    types: [closed]

jobs:
  remove-label:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Remove "needs PR" label
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const issue = context.issue; // context of the issue
          const needsPR = "needs PR"; // label to be removed
          const { data: issueData } = await github.issues.get({
            owner: issue.owner,
            repo: issue.repo,
            issue_number: issue.number,
          });
          if (issueData.labels.map((label) => label.name).includes(needsPR)) {
            await github.issues.removeLabel({
              owner: issue.owner,
              repo: issue.repo,
              issue_number: issue.number,
              name: needsPR,
            });
          }
